const { RELEASE_RULES, CHANGELOG_TYPES } = require('./release.rules.cjs');

module.exports = {
    // You can find out more about the configuration of this file here https://semantic-release.gitbook.io/semantic-release/usage/configuration
    "branches": [
        { "name": 'master' },
        { "name": 'release/*', "prerelease": 'rc' },
        { "name": 'develop', "prerelease": 'alpha' },
    ],
    "tagFormat": '${version}',
    // Plugins https://semantic-release.gitbook.io/semantic-release/extending/plugins-list
    "plugins": [
        [
            // Analyzes commits and determines which release version should be released.
            '@semantic-release/commit-analyzer',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will increase the release version
                "releaseRules": RELEASE_RULES,
            },
        ],
        [
            // Add release notes
            '@semantic-release/release-notes-generator',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will be described in the release notes
                "presetConfig": { "types": CHANGELOG_TYPES },
            },
        ],
        [
            // Writing release notes to a changelog
            '@semantic-release/changelog',
            { "changelogFile": 'CHANGELOG.md' },
        ],
        [
            // Plugin for commits changes
            '@semantic-release/git',
            {
                "assets": ['CHANGELOG.md'],
                "message":
                    'dosc(release): update changelog [skip ci]\n\n' +
                    'Automatically generated by semantic-release'
            },
        ],
        [
            // Release to Github with builded files 
            '@semantic-release/github', 
            {
                "assets": [
                    { "path": 'dist/*' }
                ],
                "successComment": false,
                "failTitle": false,
                "failComment": false,
                "labels": false,
            }
        ],
    ],
};